AWSTemplateFormatVersion: '2010-09-09-OC'
Description: Default organization blueprint

# https://aws.amazon.com/blogs/mt/best-practices-for-organizational-units-with-aws-organizations/
Organization:

  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: '{{johnnybianco}}-management'
      RootEmail: johnawhitedevops@{{gmail.com}}
      AccountName: Management Account
      AccountId: '{{817326272961}}'
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: johnawhitedevops@{{gmail.com}}

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      DefaultBuildAccessRoleName: OrganizationFormationBuildAccessRole

  # Organizational Unit used for Production workloads
  ProdOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: prod
      Accounts: []

  # Organizational Unit used for the Software Development Life Cycle of each team
  SdlcOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: sdlc
      Accounts: []

  # Organizational Unit used for shared infrastructure services
  SharedOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref OrgBuildAccount
        - !Ref SecurityAccount
        - !Ref LogArchiveAccount

  # Organizational Unit that contains accounts to be deleted from organization
  SuspendedOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: suspended
      Accounts: []

  SecurityAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: '{{johnnybianco}}-security'
      AccountName: Security Account
      RootEmail: johnawhitedevops+sec@{{gmail.com}}
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: security@{{gmail.com}}

  LogArchiveAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: '{{johnnybianco}}-log-archive'
      AccountName: Log Archive Account
      RootEmail: johnawhitedevops+log@{{gmail.com}}
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: log-archive@{{gmail.com}}

  OrgBuildAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: '{{johnnybianco}}-org-build'
      AccountName: Organization Build Account
      RootEmail: johnawhitedevops+svcs@{{gmail.com}}
      Tags:
        budget-alarm-threshold: 200
        budget-alarm-threshold-email-recipient: me@{{gmail.com}}
